name: Job
on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Current CI No.'
        required: false
        default: '0'
        type: string

permissions:
  contents: read
  actions: write

env:
  PROXY_URL: ${{secrets.PROXY_URL}}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
        cache: "pip"
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Run Job
      run: python job.py "${{ github.event.inputs.count }}" "${{ github.token }}" "${{ github.repository }}"

